### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by jokerigno** [xnappo/VirtualEpisodes#1]
Hi,
just found out whit looking at a post in emby forum.

Can you please give me an overview?

You have "something" in sonarr that add all your interested contents from netflix-amazon for example? Because I've searched for list of the catalogue available in my country on those services without luck.

Then you use this to create dummy files that are played on your android tv (i have an nvidia shield) using "original" app, right?

TY!

**Comment by jokerigno** [comment]
UPDATE: found out istructions in old release.

https://github.com/xnappo/VirtualEpisodes/tree/c60329a990e4c7f97d26ca7f70d0039cecc17390

Why are not available anymore?

**Comment by xnappo** [comment]
Thanks for pointing this out, I was messing with making the Kodi more of a real plugin and accidently overwrote the readme :)
